### ISSUE TITLE
Historia de la Base de Datos 2

### ISSUE THREAD

**Issue by PaylemanC** [facuezeperalta/grupo2ISPC#4]
Desde los 80' hasta la ACTUALIDAD.

**Comment by TamaraPiccinni** [comment]
** Década de los 80 – SGBD Relacionales.**

-Comenzó el auge de la comercialización de los sistemas relacionales, y SQL comenzó a ser el estándar de la industria, ya que las bases de datos relacionales con su sistema de tablas (compuesta por filas y columnas) pudieron competir con las bases jerárquicas y de red.
Los Ordenadores personales

-Durante los años ochenta aparecen y se extienden muy rápidamente los ordenadores personales. También surge software para equipos monousuario (por ejemplo dBase, Access), con los cuales es muy fácil crear y utilizar conjuntos de datos, que se denominan personal data bases. 

-Se desarrolló el SQL (Structured Query Language), un lenguaje de consultas. con el fin de recuperar información de una base de datos y a su vez, hacer cambios sobre esa misma base, de forma sencilla. Permitía analizar gran cantidad de información y especificar varios tipos de operaciones con la misma información.
- SQL comenzó a ser el modelo estándar de las industrias, con su base de datos bajo un sistema de tablas (filas y columnas).

-El ORACLE está considerado como uno de los sistemas de bases de datos más completos del mundo, su dominio en el mercado fue casi total hasta muchos años después, pero esto cambió con la aparición del SQL Server de Microsoft.

-otros Sistemas Administradores de Bases de Datos Relacionales, como PostgreSQL, MySQL o Firebird aparecieron posteriormente en la década de 1990. Igualmente se da inicio a las bases de datos que se orientaban a los objetos

**Comment by TamaraPiccinni** [comment]
**Década de los 90: Distribución, C/S y 4GL**

-los SGBD relacionales ya se utilizaban prácticamente en todas las empresas.
-La necesidad de tener una visión global de la empresa y de interrelacionar diferentes aplicaciones que utilizan BD diferentes, junto con la facilidad quedan las redes para la intercomunicación entre ordenadores, ha conducido a los SGBD actuales, que permiten que un programa pueda trabajar con diferentes BD como si se tratase de una sola. Es lo se conoce como base de datos distribuida.
-La facilidad para disponer de distribución de datos no es la única razón del gran éxito de los entornos C/S en los años noventa. Tal vez el motivo fundamental ha sido la flexibilidad para construir y hacer crecer la configuración informática global de la empresa, así como de hacer modificaciones en ella, mediante hardware y software muy estándar y barato.
-El éxito de las BD, incluso en sistemas personales, ha llevado a la aparición de los Fourth Generation Languages (4GL), lenguajes muy fáciles y potentes, especializados en el desarrollo de aplicaciones fundamentadas en BD.

**Comment by TamaraPiccinni** [comment]
**Tendencias actuales**
-La incorporación de tecnologías multimedia –imagen y sonido – en los SI hace necesario que los SGBD relacionales acepten atributos de estos tipos.
-Los SGBD más recientes ya incorporaban esta posibilidad, y abren un amplio mercado de TAD predefinidos o librerías de clases.
-La utilización de lenguajes como C++ o Java requiere que los SGBD relacionales se adapten a ellos con interfaces adecuadas. La rápida adopción de la web a los SI hace que los SGBD incorporen recursos para ser servidores de páginas web, como por ejemplo la inclusión de SQL en guiones HTML, SQL incorporado en Java, etc.
-Durante estos últimos años se ha empezado a extender un tipo de aplicación de las BD denominado Data Warehouse, o almacén de datos, que también produce algunos cambios en los SGBD relacionales del mercado. os almacenes de datos se utilizan exclusivamente para hacer consultas, de forma especial para que lleven a cabo estudios los analistas financieros, los analistas de mercado, etc.
- Los SGBD actuales tienen herramientas que permiten
*crear y mantener réplicas.
*consolidar datos de orígenes diferentes
crear estructuras físicas que soporten eficientemente el análisis multidimensional.

**Comment by TamaraPiccinni** [comment]
**Gestores de Bases de Datos**
-Gestión de Bases de Datos es un software que sirve de interfaz entre la base de datos, el usuario y las aplicaciones que se utilizan.

-La mayoría de las bases de datos se presentan en formato digital
-Esto ofrece un amplio abanico de soluciones al problema de almacenamiento de datos.
-Los gestores de bases de datos, Database Management System o DBMS (SGBD) son programas que permiten almacenar y luego acceder a los datos de forma estructurada y rápida. Las aplicaciones más usadas son para gestiones de empresas e instituciones públicas, así como en entornos científicos, para almacenar la información experimental.
