### ISSUE TITLE
Software 

### ISSUE THREAD

**Issue by PaylemanC** [facuezeperalta/grupo2ISPC#8]
* Características.
* Desarrollo y proceso de Desarollo.
* Modelos. 
* Ciclo de Vida.

**Comment by facuezeperalta** [comment]
**Características:** 
 * Intangible.
 * Tiene alto contenido intelectual 
 * Se desarrolla es humano intensivo, basado en equipos y construidos en proyectos.
 * Se desarrolla, no se manufactura.
 * no se desgasta
 * se construye a medida.

**Desarrollo:**
- Define un conjunto completo de
actividades necesarias para transformar
los requerimientos
de un usuario en un producto.

**Procesos de desarrollo:** Podemos mencionar:
* Definidos y Secuenciales.
*  Empíricos.

**Ciclo de vida:**
